In [165]:
import pandas as pd
import numpy as np

In [166]:
df=pd.read_csv("Housing.csv")

In [167]:
df.head()

price  lotsize  bedrooms  bathrms  stories driveway recroom fullbase  \
0  42000.0     5850         3        1        2      yes      no      yes   
1  38500.0     4000         2        1        1      yes      no       no   
2  49500.0     3060         3        1        1      yes      no       no   
3  60500.0     6650         3        1        2      yes     yes       no   
4  61000.0     6360         2        1        1      yes      no       no   

  gashw airco  garagepl prefarea  
0    no    no         1       no  
1    no    no         0       no  
2    no    no         0       no  
3    no    no         0       no  
4    no    no         0       no

In [168]:
df=pd.get_dummies(df,drop_first=True)

In [169]:
df.head()

price  lotsize  bedrooms  bathrms  stories  garagepl  driveway_yes  \
0  42000.0     5850         3        1        2         1             1   
1  38500.0     4000         2        1        1         0             1   
2  49500.0     3060         3        1        1         0             1   
3  60500.0     6650         3        1        2         0             1   
4  61000.0     6360         2        1        1         0             1   

   recroom_yes  fullbase_yes  gashw_yes  airco_yes  prefarea_yes  
0            0             1          0          0             0  
1            0             0          0          0             0  
2            0             0          0          0             0  
3            1             0          0          0             0  
4            0             0          0          0             0

In [170]:
df.shape

(546, 12)

In [171]:
X=df.iloc[:,1:]

In [172]:
Y=df.iloc[:,0]

In [173]:
X.shape

(546, 11)

In [174]:
Y.shape

(546,)

In [175]:
from sklearn.preprocessing import MinMaxScaler

In [181]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(strategy='mean')

In [182]:
X_impute=imp.fit_transform(X)

In [183]:
X_impute=pd.DataFrame(X_impute,columns=X.columns)

In [184]:
X_impute.head()

lotsize  bedrooms  bathrms  stories  garagepl  driveway_yes  recroom_yes  \
0   5850.0       3.0      1.0      2.0       1.0           1.0          0.0   
1   4000.0       2.0      1.0      1.0       0.0           1.0          0.0   
2   3060.0       3.0      1.0      1.0       0.0           1.0          0.0   
3   6650.0       3.0      1.0      2.0       0.0           1.0          1.0   
4   6360.0       2.0      1.0      1.0       0.0           1.0          0.0   

   fullbase_yes  gashw_yes  airco_yes  prefarea_yes  
0           1.0        0.0        0.0           0.0  
1           0.0        0.0        0.0           0.0  
2           0.0        0.0        0.0           0.0  
3           0.0        0.0        0.0           0.0  
4           0.0        0.0        0.0           0.0

In [185]:
from sklearn.preprocessing import MinMaxScaler

In [192]:
scaler = MinMaxScaler()
X_impute=scaler.fit_transform(X_impute)


In [195]:

X_impute=pd.DataFrame(X_impute,columns=X.columns)

In [196]:
X_impute.head()

lotsize  bedrooms  bathrms   stories  garagepl  driveway_yes  recroom_yes  \
0  0.288660       0.4      0.0  0.333333  0.333333           1.0          0.0   
1  0.161512       0.2      0.0  0.000000  0.000000           1.0          0.0   
2  0.096907       0.4      0.0  0.000000  0.000000           1.0          0.0   
3  0.343643       0.4      0.0  0.333333  0.000000           1.0          1.0   
4  0.323711       0.2      0.0  0.000000  0.000000           1.0          0.0   

   fullbase_yes  gashw_yes  airco_yes  prefarea_yes  
0           1.0        0.0        0.0           0.0  
1           0.0        0.0        0.0           0.0  
2           0.0        0.0        0.0           0.0  
3           0.0        0.0        0.0           0.0  
4           0.0        0.0        0.0           0.0

In [197]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [198]:
X_train,X_test,Y_train,Y_test=train_test_split(X_impute,Y,test_size=0.2,random_state=7)

In [199]:
lr=LinearRegression()

In [200]:
lr.fit(X_train,Y_train)

LinearRegression()

In [204]:
Y_pre=lr.predict(X_test)
Y_pre

array([ 91803.17191001,  52077.11250189,  54058.15507333,  83760.61839679,
       114355.91512197,  64131.7351305 ,  73230.01877465,  82300.24407459,
        40452.71786628,  46613.45285814,  96711.87375309,  54241.71624291,
        38630.12948818,  94999.12742357,  58990.06927695,  94763.3936964 ,
        44801.39220934,  79490.54412977,  68595.4876103 ,  62100.66411972,
        82182.53715682,  80840.02444354,  67993.77063821,  61020.67391247,
        83558.36143708,  90229.11934395,  54264.17828773,  72902.47248129,
        69699.37115398,  36050.89897863, 119159.05981312,  89348.84017486,
        56235.0816801 ,  73418.67029738,  75648.06770664,  41284.52616467,
        78266.81878323,  49236.17793338,  56285.3082898 , 125222.66615965,
        80634.81778801,  32833.29262679,  42919.30809216,  77811.17432437,
        96711.87375309,  41516.87388437,  48830.08108565,  66344.08473898,
        65213.93051229,  40179.11428613,  69512.50321311,  92239.9393581 ,
        94377.25912342,  

5850	3	1	2	1	1	0	1	0	0	0

In [213]:
my_pred=lr.predict([[0.16151,0.2,0.0,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0,0.0]])

In [214]:
my_pred

array([41516.77003198])

In [80]:
Y_pre

array([ 84000.,  45000.,  71900.,  58000., 103000.,  60500.,  55000.,
        74500.,  42000.,  49900.,  82500.,  46000.,  33000.,  87000.,
        61000., 118500.,  57000.,  59900.,  69900.,  34000.,  80000.,
        87000.,  60000.,  50000.,  60000.,  85000.,  48000.,  82000.,
        60000.,  26500., 155000., 106000.,  70000.,  65000., 106500.,
        38000.,  57500.,  50000.,  70100., 145000.,  79000.,  36000.,
        48000.,  88000.,  94000.,  49000.,  50000.,  52000.,  64900.,
        25000.,  80000.,  82000.,  95000.,  47000.,  86000.,  58900.,
        61500.,  68000.,  42300.,  50000.,  52000.,  52900., 114900.,
        30000.,  46200.,  46000., 108000.,  85000.,  59500.,  59000.,
        66500.,  80000.,  85000.,  44000.,  65000.,  47000.,  93000.,
        49000.,  27000.,  85000.,  25245.,  65000.,  33500.,  63500.,
        82000.,  67000.,  75000.,  49500.,  73000.,  62000.,  47600.,
       145000.,  34000.,  62900.,  57000.,  42000., 106000.,  48000.,
        88500., 1300

In [82]:
Y_pred=pd.DataFrame(Y_pre)

In [86]:
df_new=pd.concat([X_test,Y_pred])

In [88]:
df_new

0  airco_yes  bathrms  bedrooms  driveway_yes  fullbase_yes  \
538      NaN        1.0      2.0       3.0           1.0           0.0   
70       NaN        0.0      1.0       2.0           1.0           0.0   
505      NaN        0.0      1.0       2.0           1.0           1.0   
221      NaN        1.0      1.0       4.0           1.0           1.0   
520      NaN        1.0      2.0       4.0           1.0           0.0   
..       ...        ...      ...       ...           ...           ...   
105  32500.0        NaN      NaN       NaN           NaN           NaN   
106  74900.0        NaN      NaN       NaN           NaN           NaN   
107  75000.0        NaN      NaN       NaN           NaN           NaN   
108  62900.0        NaN      NaN       NaN           NaN           NaN   
109  75000.0        NaN      NaN       NaN           NaN           NaN   

     garagepl  gashw_yes  lotsize     price  recroom_yes  stories  
538       0.0        0.0   6500.0   84000.0          0.0      3.0  
70        2.0        0.0   4095.0   45000.0          0.0      1.0  
505       0.0        0.0   4800.0   71900.0          1.0      1.0  
221       2.0        0.0   3000.0   58000.0          0.0      3.0  
520       1.0        0.0   7680.0  103000.0          1.0      4.0  
..        ...        ...      ...       ...          ...      ...  
105       NaN        NaN      NaN       NaN          NaN      NaN  
106       NaN        NaN      NaN       NaN          NaN      NaN  
107       NaN        NaN      NaN       NaN          NaN      NaN  
108       NaN        NaN      NaN       NaN          NaN      NaN  
109       NaN        NaN      NaN       NaN          NaN      NaN  

[220 rows x 12 columns]

In [65]:
df1=pd.DataFrame(df)

In [67]:
df1.describe()

price       lotsize    bedrooms     bathrms     stories  \
count     546.000000    546.000000  546.000000  546.000000  546.000000   
mean    68121.597070   5150.265568    2.965201    1.285714    1.807692   
std     26702.670926   2168.158725    0.737388    0.502158    0.868203   
min     25000.000000   1650.000000    1.000000    1.000000    1.000000   
25%     49125.000000   3600.000000    2.000000    1.000000    1.000000   
50%     62000.000000   4600.000000    3.000000    1.000000    2.000000   
75%     82000.000000   6360.000000    3.000000    2.000000    2.000000   
max    190000.000000  16200.000000    6.000000    4.000000    4.000000   

         garagepl  driveway_yes  recroom_yes  fullbase_yes   gashw_yes  \
count  546.000000    546.000000   546.000000    546.000000  546.000000   
mean     0.692308      0.858974     0.177656      0.349817    0.045788   
std      0.861307      0.348367     0.382573      0.477349    0.209216   
min      0.000000      0.000000     0.000000      0.000000    0.000000   
25%      0.000000      1.000000     0.000000      0.000000    0.000000   
50%      0.000000      1.000000     0.000000      0.000000    0.000000   
75%      1.000000      1.000000     0.000000      1.000000    0.000000   
max      3.000000      1.000000     1.000000      1.000000    1.000000   

        airco_yes  prefarea_yes  
count  546.000000    546.000000  
mean     0.316850      0.234432  
std      0.465675      0.424032  
min      0.000000      0.000000  
25%      0.000000      0.000000  
50%      0.000000      0.000000  
75%      1.000000      0.000000  
max      1.000000      1.000000

In [216]:
from sklearn.metrics  import mean_squared_error

In [218]:
mean_squared_error(Y_test, Y_pred)

1.5641233401002705e-24

In [219]:
from sklearn.metrics import accuracy_score

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets